/*
    Detect files created with msfvenom
*/
rule Msf_venom {
    meta:
        description = "Detect files generated by msfvenom"
    	version = "0.1"
    strings:
        $s1 = "msfvenom"
        $s2 = "Metasploit Payload"
        $s3 = "Meterpreter"

    condition:
        2 of ($s*)
}


